export const JWT_TOKEN_SECRET = 'JWT_TOKEN_SECRET';
export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
export const JWT_TOKEN_EXPIRATION_EXPIRATION_TIME_SECONDS =
  'JWT_TOKEN_EXPIRATION_EXPIRATION_TIME_SECONDS';
export const JWT_REFRESH_TOKEN_EXPIRATION_EXPIRATION_TIME_SECONDS =
  'JWT_REFRESH_TOKEN_EXPIRATION_EXPIRATION_TIME_SECONDS';
