export const JWTAdapterToken = 'JWTAdapterToken';
export const JWTConfigAdapterToken = 'JWTConfigAdapterToken';
export const BcryptAdapterToken = 'BcryptAdapterToken';

export const CREATE_COOKIE_WITH_ACCESS_TOKEN_USE_CASE =
  'CREATE_COOKIE_WITH_ACCESS_TOKEN_USE_CASE';
export const CREATE_COOKIE_WITH_REFRESH_TOKEN_USE_CASE =
  'CREATE_COOKIE_WITH_REFRESH_TOKEN_USE_CASE';
export const GET_USER_IF_REFRESH_TOKEN_IS_VALID_USE_CASE =
  'GET_USER_IF_REFRESH_TOKEN_IS_VALID_USE_CASE';
export const VALIDATE_CREDENTIALS_USE_CASE = 'VALIDATE_CREDENTIALS_USE_CASE';
export const LOGOUT_USE_CASE = 'LOGOUT_USE_CASE';
export const REGISTER_USE_CASE = 'REGISTER_USE_CASE';
export const LOGIN_USE_CASE = 'LOGIN_USE_CASE';
export const VALIDATE_ACCESS_TOKEN_USE_CASE = 'VALIDATE_ACCESS_TOKEN_USE_CASE';
export const REFRESH_ACCESS_TOKEN_COOKIE_USE_CASE = 'REFRESH_ACCESS_TOKEN_COOKIE_USE_CASE';